name: action-slack
description: You can notify slack of GitHub Actions.
author: 8398a7
inputs:
  template:
    description: Slack message template (error, success, deployed, ready_for_qa, released)
    required: true
    default: success
  title:
    description: Message Title
    required: true
  header:
    description: Message Header
    required: true
  ticket:
    description: Jira Ticket
    required: true
  token:
    description: Slack Token
    required: true
runs:
  using: "composite"
  steps:
    - uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took
        if: inputs.template == 'error'
        custom_payload: |
          {
            "text": "${{ inputs.title }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "plain_text",
                  "text": "${{ inputs.header }}",
                  "emoji": true
                }
              }
            ],
            "attachments": [
              {
                "color": "#c33124",
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Ticket:* ${{ inputs.ticket }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Status:* ${{ job.status }}"
                      }
                    ]
                  }
                ]
              },
              {
                "color": "#1982c4",
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Author:* ${{ github.event.pusher.email }}"
                      }
                    ]
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.token }}
branding:
  icon: bell
  color: blue
